jdbc:
  enabled: false
  driver-class: com.mysql.cj.jdbc.Driver
  druid:
    enabled: false
    context-path: /druid/*
    username: admin
    password: admin
  master:
    enabled: false
    url:
    username:
    password:
    db-list:
      db1:
        enabled: false
        url:
        username:
        password:
